import {
  CloudDownload,
  CreditCard,
  FileSpreadsheet,
  FileUp,
  Landmark,
  Settings2,
  ShieldCheck,
  Sun,
  Wallet,
} from "lucide-react";
import type { TransactionListItem } from "@/components/shared";

export const transactionItems: TransactionListItem[] = [
  {
    id: "tx-01",
    day: "28",
    weekday: "Mon",
    emoji: "🍛",
    title: "Tea & buns",
    category: "Food",
    account: "Wallet",
    amount: "Rs. 280.00",
    type: "expense",
    note: "",
  },
  {
    id: "tx-02",
    day: "27",
    weekday: "Sun",
    emoji: "🛵",
    title: "Petrol bike",
    category: "Transport",
    account: "Wallet",
    amount: "Rs. 2,500.00",
    type: "expense",
    note: "",
  },
  {
    id: "tx-03",
    day: "27",
    weekday: "Sun",
    emoji: "🍛",
    title: "Lunch - rice & curry",
    category: "Food",
    account: "Wallet",
    amount: "Rs. 650.00",
    type: "expense",
    note: "",
  },
  {
    id: "tx-04",
    day: "27",
    weekday: "Sun",
    emoji: "🤝",
    title: "From akka",
    category: "Other",
    account: "People's",
    amount: "Rs. 15,000.00",
    type: "income",
    note: "Trip to Ella",
  },
  {
    id: "tx-05",
    day: "27",
    weekday: "Sun",
    emoji: "⇄",
    title: "People's to Credit Card",
    category: "Card payment",
    account: "Transfer",
    amount: "Rs. 18,450.00",
    type: "transfer",
    note: "",
  },
  {
    id: "tx-06",
    day: "26",
    weekday: "Sat",
    emoji: "🎓",
    title: "Master dev course",
    category: "Career",
    account: "Commercial",
    amount: "Rs. 54,034.80",
    type: "expense",
    note: "Annual subscription",
  },
  {
    id: "tx-07",
    day: "26",
    weekday: "Sat",
    emoji: "🥂",
    title: "Kasun's wedding gift",
    category: "Social Life",
    account: "Wallet",
    amount: "Rs. 10,000.00",
    type: "expense",
    note: "",
  },
  {
    id: "tx-08",
    day: "25",
    weekday: "Fri",
    emoji: "💼",
    title: "September salary",
    category: "Salary",
    account: "Commercial",
    amount: "Rs. 285,000.00",
    type: "income",
    note: "",
  },
  {
    id: "tx-09",
    day: "25",
    weekday: "Fri",
    emoji: "🍛",
    title: "Keells groceries",
    category: "Food",
    account: "Credit Card",
    amount: "Rs. 4,862.40",
    type: "expense",
    note: "",
  },
];

export const accountItems = [
  {
    id: "wallet",
    name: "Wallet",
    detail: "Cash in hand",
    balance: "Rs. 8,420.50",
    type: "cash",
    icon: Wallet,
  },
  {
    id: "commercial",
    name: "Commercial",
    detail: "Savings · •• 2381",
    balance: "Rs. 246,902.33",
    type: "bank",
    icon: Landmark,
  },
  {
    id: "peoples",
    name: "People's",
    detail: "Savings · •• 0932",
    balance: "Rs. 37,215.45",
    type: "bank",
    icon: Landmark,
  },
  {
    id: "boc",
    name: "BOC",
    detail: "ධනයෝජන · •• 5520",
    balance: "Rs. 60,810.00",
    type: "bank",
    icon: Landmark,
  },
  {
    id: "credit-card",
    name: "People's Credit Card",
    detail: "•• 6184 · Due Oct 15",
    balance: "- Rs. 18,000.00",
    type: "credit_card",
    icon: CreditCard,
  },
];

export const expenseCategories = [
  {
    name: "Food",
    emoji: "🍛",
    spent: "Rs. 48,620",
    budget: "Rs. 60,000",
    percent: 81,
    color: "#e96b58",
  },
  {
    name: "Transport",
    emoji: "🛵",
    spent: "Rs. 22,450",
    budget: "Rs. 35,000",
    percent: 64,
    color: "#4c8dff",
  },
  {
    name: "Bills",
    emoji: "🧾",
    spent: "Rs. 18,900",
    budget: "Rs. 25,000",
    percent: 76,
    color: "#f5a524",
  },
  {
    name: "Career",
    emoji: "🎓",
    spent: "Rs. 54,035",
    budget: "Rs. 60,000",
    percent: 90,
    color: "#a78bfa",
  },
  {
    name: "Social Life",
    emoji: "🥂",
    spent: "Rs. 21,500",
    budget: "Rs. 30,000",
    percent: 72,
    color: "#3fb97f",
  },
  {
    name: "Other",
    emoji: "📦",
    spent: "Rs. 9,840",
    budget: "Rs. 20,000",
    percent: 49,
    color: "#e7a7c2",
  },
];

export const trendData = [
  { month: "Oct", income: 320, expense: 210, net: 80 },
  { month: "Nov", income: 325, expense: 235, net: 90 },
  { month: "Dec", income: 410, expense: 260, net: 130 },
  { month: "Jan", income: 330, expense: 205, net: 105 },
  { month: "Feb", income: 330, expense: 220, net: 115 },
  { month: "Mar", income: 338, expense: 225, net: 113 },
  { month: "Apr", income: 350, expense: 240, net: 110 },
  { month: "May", income: 360, expense: 230, net: 130 },
  { month: "Jun", income: 355, expense: 260, net: 95 },
  { month: "Jul", income: 390, expense: 240, net: 150 },
  { month: "Aug", income: 380, expense: 270, net: 110 },
  { month: "Sep", income: 414, expense: 226, net: 188 },
];

export const recurringItems = [
  {
    name: "Mobile data",
    detail: "Bills · Wallet · Due Oct 05",
    amount: "Rs. 300.00",
    status: "Active",
  },
  {
    name: "Netflix",
    detail: "Bills · Credit Card · Due Oct 12",
    amount: "Rs. 2,990.00",
    status: "Due today",
  },
  {
    name: "Loan installment",
    detail: "Family · Commercial · Due Oct 25",
    amount: "Rs. 15,000.00",
    status: "Active",
  },
  {
    name: "Salary",
    detail: "Salary · Commercial · Due Oct 25",
    amount: "Rs. 285,000.00",
    status: "Active",
  },
];

export const settingsItems = [
  {
    key: "categories",
    title: "Categories",
    description: "Income and expense groups",
    icon: Settings2,
  },
  {
    key: "accounts",
    title: "Accounts",
    description: "Manage accounts and card settings",
    icon: Wallet,
  },
  {
    key: "templates",
    title: "Templates",
    description: "Saved transaction shortcuts",
    icon: FileSpreadsheet,
  },
  {
    key: "security",
    title: "Security",
    description: "PIN, passkeys, and auto-lock",
    icon: ShieldCheck,
  },
  {
    key: "backup",
    title: "Backup",
    description: "Export and restore your ledger",
    icon: CloudDownload,
  },
  {
    key: "import",
    title: "Import",
    description: "Bring in a CSV or Excel file",
    icon: FileUp,
  },
  {
    key: "preferences",
    title: "Preferences",
    description: "Theme, dates, and defaults",
    icon: Sun,
  },
];
